/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aut25_vertx_NDPIWrapper */

#ifndef _Included_com_aut25_vertx_NDPIWrapper
#define _Included_com_aut25_vertx_NDPIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_aut25_vertx_NDPIWrapper_init
  (JNIEnv *, jobject);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    createFlow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_aut25_vertx_NDPIWrapper_createFlow
  (JNIEnv *, jobject);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    analyzePacket
 * Signature: ([BJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aut25_vertx_NDPIWrapper_analyzePacket
  (JNIEnv *, jobject, jbyteArray, jlong, jlong);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    cleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_aut25_vertx_NDPIWrapper_cleanup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    getFlowRiskMask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_aut25_vertx_NDPIWrapper_getFlowRiskMask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    getFlowRiskScore
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_aut25_vertx_NDPIWrapper_getFlowRiskScore
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    getFlowRiskLabel
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aut25_vertx_NDPIWrapper_getFlowRiskLabel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    getFlowRiskSeverity
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aut25_vertx_NDPIWrapper_getFlowRiskSeverity
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
