/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aut25_vertx_NDPIWrapper */

#ifndef _Included_com_aut25_vertx_NDPIWrapper
#define _Included_com_aut25_vertx_NDPIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aut25_vertx_NDPIWrapper_init
  (JNIEnv *, jobject);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    analyzePacket
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aut25_vertx_NDPIWrapper_analyzePacket
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_aut25_vertx_NDPIWrapper
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aut25_vertx_NDPIWrapper_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
